### PR TITLE
Add tests for ClassGroup/JsonAdaptedClassGroup, Delete

### LINKED ISSUE #68: Update tests for ClassGroup, CLassGroupId and UniqueClassGroupList

### PR DESCRIPTION
**Pull request by jxt00**
Added tests for the following classes:
* ClassGroupId, ClassGroup, UniqueClassGroupList (Closes #68 )
  * `ClassGroup#hasStudent()` is commented out as it fails occasionally
* WeekId, Lesson
* Attendance, StudentAttendance
* DeleteCommandParser, DeleteCommand
  * `DeleteCommand#*assessmentTests` are commented out until `TypicalAssessments` is implemented
  * `DeleteCommand#*studentTests` are commented out until I fix it next time... (next week)

Added the following helper classes:
* StudentAttendanceBuilder, LessonBuilder,
* TypicalStudentAttendances, TypicalLessons

Updated the following classes:
* ClassGroupBuilder (`withLessons` is a bit buggy but all tests pass)
* TypicalClassGroups, TypicalIndexes (`ENTITY` instead of `PERSON`)
* CommandTestUtil, CommandParserTestUtil

Removed AB3 Delete and Edit tests

### CODE REVIEW

**Review by Gernene — COMMENTED** [review]
Is there a reason so many AB3 test were modified? Aren't these the files "leftovers"?

**Comment by lkldev** [comment]
I think you can remove the AB3 test cases if you are done replicating it, since we don't need it anymore

**Review by lkldev — APPROVED** [review]
LGTM

**Review by wxliong — APPROVED** [review]
LGTM

**Pull request merged**
