### PR TITLE
Add delete feature and update Model component in DG

### LINKED ISSUE #102: Add delete feature to Developer Guide's Implementation section

### LINKED ISSUE #105: Update Model Component in Developer Guide

### PR DESCRIPTION
**Pull request by jxt00**
Resolves #102 
Resolves #105 

For #105, would it better to remove the attributes `StudentId`, `Name` etc. from the ModelClassDiagram as it is very cluttered and messy.

### CODE REVIEW

**Comment by lkldev** [comment]
Yeap, agree, we can separate the attributes for all 3 entities into another class, and to show that they all implement entity too

**Review by Gernene — COMMENTED** [review]
docs/images/AB3ModelClassDiagram.png

It seems like this is still using AddressBook and not TAssist?

**Review by Gernene — APPROVED** [review]
docs/images/AB3ModelClassDiagram.png

It seems like this is still using AddressBook and not TAssist?

**Comment by jxt00** [comment]
> docs/images/AB3ModelClassDiagram.png
> 
> It seems like this is still using AddressBook and not TAssist?

I'm not too sure how to reply to your comment, so I'll just comment here.  I renamed the old `ModelClassDiagram.png` to `AB3ModelClassDiagram.png` to differentiate between the model images used for TAssist and AddressBook. The current DG is using the correct updated diagram.

**Review by lkldev — APPROVED** [review]
LGTM 👍

**Pull request merged**
